#!/bin/sh

rm -Rf ./vendor/*
wget http://www.gpo.gov/fdsys/pkg/CFR-2013-title48-vol2/xml/CFR-2013-title48-vol2-chap1-subchapH.xml -P vendor
wget http://www.gpo.gov/fdsys/pkg/CFR-2013-title48-vol3/xml/CFR-2013-title48-vol3-chap2-subchapH.xml -P vendor
